//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIPG_FrameWork.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12345")]
        public string wrong_password {
            get {
                return ((string)(this["wrong_password"]));
            }
            set {
                this["wrong_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ertyu")]
        public string wrong_username {
            get {
                return ((string)(this["wrong_username"]));
            }
            set {
                this["wrong_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empty_username {
            get {
                return ((string)(this["empty_username"]));
            }
            set {
                this["empty_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empty_password {
            get {
                return ((string)(this["empty_password"]));
            }
            set {
                this["empty_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Login1_UserName")]
        public string Username_TextBox {
            get {
                return ((string)(this["Username_TextBox"]));
            }
            set {
                this["Username_TextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Login1_Password")]
        public string Password_TextBox {
            get {
                return ((string)(this["Password_TextBox"]));
            }
            set {
                this["Password_TextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Login1_LoginButton")]
        public string LoginButton {
            get {
                return ((string)(this["LoginButton"]));
            }
            set {
                this["LoginButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"@@****")]
        public string Special_Characters {
            get {
                return ((string)(this["Special_Characters"]));
            }
            set {
                this["Special_Characters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@id=\'waxnav\']/ul/li[3]/div/a/span")]
        public string Approval_Page {
            get {
                return ((string)(this["Approval_Page"]));
            }
            set {
                this["Approval_Page"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@id=\'waxnav\']/ul/li[6]/div/a/span")]
        public string Help_Page {
            get {
                return ((string)(this["Help_Page"]));
            }
            set {
                this["Help_Page"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@id=\'waxnav\']/ul/li[2]/div/a/span")]
        public string List_Page {
            get {
                return ((string)(this["List_Page"]));
            }
            set {
                this["List_Page"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a > span")]
        public string New_Page {
            get {
                return ((string)(this["New_Page"]));
            }
            set {
                this["New_Page"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@id=\'waxnav\']/ul/li[5]/div/a/span")]
        public string Reports_Page {
            get {
                return ((string)(this["Reports_Page"]));
            }
            set {
                this["Reports_Page"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Logout")]
        public string Logout_Link {
            get {
                return ((string)(this["Logout_Link"]));
            }
            set {
                this["Logout_Link"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("View Branches")]
        public string View_Branches {
            get {
                return ((string)(this["View_Branches"]));
            }
            set {
                this["View_Branches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("View Fees")]
        public string View_Fees {
            get {
                return ((string)(this["View_Fees"]));
            }
            set {
                this["View_Fees"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("View Merchants")]
        public string View_Merchants {
            get {
                return ((string)(this["View_Merchants"]));
            }
            set {
                this["View_Merchants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("View Regions")]
        public string View_Regions {
            get {
                return ((string)(this["View_Regions"]));
            }
            set {
                this["View_Regions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("View User Roles")]
        public string View_User_Roles {
            get {
                return ((string)(this["View_User_Roles"]));
            }
            set {
                this["View_User_Roles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("View Users")]
        public string View_Users {
            get {
                return ((string)(this["View_Users"]));
            }
            set {
                this["View_Users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bank Transaction Report")]
        public string Bank_Report {
            get {
                return ((string)(this["Bank_Report"]));
            }
            set {
                this["Bank_Report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audit Trail")]
        public string Audit_Trail {
            get {
                return ((string)(this["Audit_Trail"]));
            }
            set {
                this["Audit_Trail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Settlement Report")]
        public string Settlement_Report {
            get {
                return ((string)(this["Settlement_Report"]));
            }
            set {
                this["Settlement_Report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Product Split Report")]
        public string Product_Split_Report {
            get {
                return ((string)(this["Product_Split_Report"]));
            }
            set {
                this["Product_Split_Report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Order Settlement Report")]
        public string Order_Settlement_Report {
            get {
                return ((string)(this["Order_Settlement_Report"]));
            }
            set {
                this["Order_Settlement_Report"] = value;
            }
        }
    }
}
